//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeVentasOnline.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int CarritoId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> EstadoCarritoNombre { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
