//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeVentasOnline.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int DetalleCompraId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> OrdenId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string TipoPago { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
