//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeVentasOnline.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int OperacionId { get; set; }
        public string OperacionNombre { get; set; }
        public Nullable<int> ModuloId { get; set; }
    
        public virtual Modulo Modulo { get; set; }
    }
}
